---
title: "Desigualdades Territorriales – Antioquia"
format: html
lang: es
bibliography: references.bib
---

A continuación se presenta la aplicación de la metodología de *brechas territoriales* para Antioquia, la cual ofrece una nueva lectura de **oportunidades** y **desafíos sociales** desde una **visión territorial** y con **enfoque diferencial**. A partir de la metodología *Pulso Social* del **Banco Interamericano de Desarrollo (BID)** [@Duryea2016Pulso2016], se asume que la política social debe **centrarse en las personas** a lo largo del **ciclo de vida** (niñez, infancia, juventud, adultez y vejez), con el fin de identificar **brechas** y **cuellos de botella** en la formación de capital humano.

Para ello se realiza una **revisión sistemática** de indicadores sociales, agrupados en dos categorías:

- **Contexto**: condiciones generales del hogar y entorno (esenciales para comprender el marco en el que se diseñan políticas).  
  - [Agua potable y saneamiento](03_Outputs/resultados_idx1_servicio.qmd)
  - [Crecimiento económico ](03_Outputs/resultados_idx6_crecimiento.qmd )
  - [Cambio climático ](03_Outputs/resultados_idx3_climatico.qmd )
  - [Pobreza ](03_Outputs/resultados_idx11_pobreza.qmd)
  - [Características de la vivienda ](03_Outputs/resultados_idx5_viviendas.qmd )
  - [Capacidad fiscal](03_Outputs/resultados_idx4_Capacidad.qmd)
  - [Desigualdad ](03_Outputs/resultados_idx7_gini.qmd)
  - [Estructura demográfica ](03_Outputs/resultados_idx8_demografica.qmd)
  - [Salud ](03_Outputs/resultados_idx12_salud.qmd)
  - [Salud Mental ](03_Outputs/resultados_idx13_saludmental.qmd)
  - [Seguridad ](03_Outputs/resultados_idx14_seguridad.qmd )
- 
- **Resultados**: situaciones sociales específicas **a lo largo del ciclo de vida**; reflejan el contexto e impactos en bienestar [@Duryea2016Pulso2016].
  - [Infancia y niñez](03_Outputs/resultados_idx9_infnin.qmd)
  - [Juventud ](03_Outputs/resultados_idx10_juventud.qmd)
  - [Adultez ](03_Outputs/resultados_idx2_Adultez.qmd)
  - [Vejez ](03_Outputs/resultados_idx15_vejez.qmd) 



# Infraestructura de datos 

La aplicación de la metodología partió de la consolidación del programa *Antioquia como vamos*, el cual es la base de la **infraestructura de datos abiertos** que habilita un análisis **flexible**, con **enfoque territorial** y **diferencial**. La infraestructura incluye la revisión de **404 indicadores** provenientes de **22 bases de datos**, con corte a **diciembre de 2021**. El **anexo técnico** describe en detalle la arquitectura de datos, fuentes, coberturas y reglas de tratamiento.

# Enfoque analítico: “las múltiples Antioquias”

La estructura de datos permite una lectura **comprensiva** de la realidad social del país y una propuesta basada en la **caracterización de tipologías territoriales** (las *múltiples Colombias*).

1. **Índices por dimensión**: primero se construyen **índices** para cada dimensión de *Pulso Social*, que **resumen** las características comunes de los indicadores que la componen.  
2. **Agrupamiento por similitud**: luego, a partir de **patrones comunes** y **similitudes** entre **todas las dimensiones**, se generan **agrupaciones** de territorios **más homogéneos**.

A este análisis lo denominamos **“las múltiples Colombias”**, porque hace visible la **diversidad de trayectorias** territoriales desde una lectura sistemática de las dimensiones por **ciclo de vida**.


---

El estudio original puede accederse [Descargar](/pdf/Desigualdades-territoriales-en-Colombia-realidades.pdf)

Descripción detallada de la metodología explicada [Descargar](/pdf/Anexo_Metodologico_PulsoSocial.pdf)
