project:
  type: website
  output-dir: ../docs
website:
  title: "Pulso Social – Antioquia"
  navbar:
    tools:
      - icon: house
        href: https://www.jcmunozmora.co/
      - icon: github
        href: https://twitter.com

    left:
      - href: index.qmd
        text: Inicio
      - href: metodologia.qmd
        text: Metodología
      - href: antioquia.qmd
        text: Antioquia
      - href: multiples_colombias.qmd
        text: Multiples Colombias
      - text: Indices
        menu:
            - href: resultados_idx1_servicio.qmd
              text: IDX 1 - Servicios
            - href: result_idx2.qmd
              text: IDX 2 - Educación
            - href: result_idx3.qmd
              text: IDX 3 - Salud
            - href: result_idx4.qmd
              text: IDX 4 - Vivienda
            - href: result_idx5.qmd
              text: IDX 5 - Empleo
            - href: result_idx6.qmd
              text: IDX 6 - Seguridad
            - href: result_idx7.qmd
              text: IDX 7 - Medio Ambiente
            - href: result_idx8.qmd
              text: IDX 8 - Participación
            - href: result_idx9.qmd
              text: IDX 9 - Cultura
            - href: result_idx10.qmd
              text: IDX 10 - Infraestructura
            - href: result_idx11.qmd
              text: IDX 11 - Movilidad
            - href: result_idx12.qmd
              text: IDX 12 - Tecnología
            - href: result_idx13.qmd
              text: IDX 13 - Inclusión
            - href: result_idx14.qmd
              text: IDX 14 - Gobernanza
            - href: result_idx15.qmd
              text: IDX 15 - Economía

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-line-numbers: false
    code-tools: false
    code-fold: true
