project:
  type: website
  output-dir: ../docs
website:
  title: "Pulso Social – Antioquia"
  navbar:
    tools:
      - icon: house
        href: https://www.jcmunozmora.co/
      - icon: github
        href: https://twitter.com

    left:
      - href: index.qmd
        text: Inicio
      - href: metodologia.qmd
        text: Metodología
      - href: antioquia.qmd
        text: Antioquia
      - href: multiples_colombias.qmd
        text: Multiples Colombias
      - text: Indices
        menu:
            - href: resultados_idx1_servicio.qmd
              text: IDX 1 - Servicios
            - href: resultados_idx2_educacion.qmd
              text: IDX 2 - Educación
            - href: resultados_idx3_salud.qmd
              text: IDX 3 - Salud
            - href: resultados_idx4_vivienda.qmd
              text: IDX 4 - Vivienda
            - href: resultados_idx5_empleo.qmd
              text: IDX 5 - Empleo
            - href: resultados_idx6_seguridad.qmd
              text: IDX 6 - Seguridad
            - href: resultados_idx7_medioambiente.qmd
              text: IDX 7 - Medio Ambiente
            - href: resultados_idx8_demografica.qmd
              text: IDX 8 - Demografía
            - href: resultados_idx9_infnin.qmd
              text: IDX 9 - Infancia y Niñez
            - href: resultados_idx10_juventud.qmd
              text: IDX 10 - Juventud
            - href: resultados_idx11_salud.qmd
              text: IDX 11 - Salud
            - href: resultados_idx12_discapacidad.qmd
              text: IDX 12 - Discapacidad
            - href: resultados_idx13_seguridad.qmd
              text: IDX 13 - Seguridad
            - href: resultados_idx14_alimentaria.qmd
              text: IDX 14 - Seguridad Alimentaria
            - href: resultados_idx15_social.qmd
              text: IDX 15 - Seguridad Social

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-line-numbers: false
    code-tools: false
    code-fold: true
